# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_press = QtWidgets.QLabel(self.centralwidget)
        self.label_press.setObjectName("label_press")
        self.gridLayout.addWidget(self.label_press, 2, 0, 1, 1)
        self.btn_start = QtWidgets.QPushButton(self.centralwidget)
        self.btn_start.setObjectName("btn_start")
        self.gridLayout.addWidget(self.btn_start, 4, 0, 1, 1)
        self.label_humi = QtWidgets.QLabel(self.centralwidget)
        self.label_humi.setObjectName("label_humi")
        self.gridLayout.addWidget(self.label_humi, 1, 0, 1, 1)
        self.label_temp = QtWidgets.QLabel(self.centralwidget)
        self.label_temp.setObjectName("label_temp")
        self.gridLayout.addWidget(self.label_temp, 0, 0, 1, 1)
        self.label_lum = QtWidgets.QLabel(self.centralwidget)
        self.label_lum.setText("")
        self.label_lum.setObjectName("label_lum")
        self.gridLayout.addWidget(self.label_lum, 3, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_press.setText(_translate("MainWindow", "Pressão"))
        self.btn_start.setText(_translate("MainWindow", "Começar"))
        self.label_humi.setText(_translate("MainWindow", "Umidade"))
        self.label_temp.setText(_translate("MainWindow", "Temperatura"))
